services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: licentra_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "6543:5432"

  backend:
    build: ./backend
    ports:
      - "4567:4567"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: licentra_development
      DATABASE_USER: myusername
      DATABASE_PASSWORD: mypassword
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend

volumes:
  postgres_data:
