services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: licentra_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "6543:5432"

  backend:
    build: ./backend
    ports:
      - "4567:4567"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: licentra_development
      DATABASE_USER: myusername
      DATABASE_PASSWORD: mypassword
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    profiles: ["proxy"]
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
      - "81:81"    # Admin-UI
    volumes:
      - ./npm-data:/data
      - ./npm-letsencrypt:/etc/letsencrypt

volumes:
  postgres_data:

