services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: licentra_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-net

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: licentra_development
      DATABASE_USER: myusername
      DATABASE_PASSWORD: mypassword
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
    networks:
      - backend-net
      - proxy-net

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    profiles: ["proxy"]
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./npm-data:/data
      - ./npm-letsencrypt:/etc/letsencrypt
    networks:
      - proxy-net

volumes:
  postgres_data:

networks:
  backend-net:
  proxy-net:
