# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bcrypt'
gem 'pg'
gem 'puma'
gem 'rackup'
gem 'rake'
gem 'sequel'
gem 'sinatra', '>= 4.1.0'
gem 'tilt', '>= 2.2.0'
gem 'erubi', '>= 1.12.0'
gem 'rack-protection'
gem 'rack-flash3'
gem 'mail'

group :development do
end

group :test do
  gem 'database_cleaner-sequel'
  gem 'fabrication'
  gem 'faker'
  gem 'rack-test', require: 'rack/test'
  gem 'rspec'
  gem 'sqlite3', '~> 1.7.3'
end

group :development, :test do
end
