source 'https://rubygems.org'

gem 'sinatra'
gem 'rackup'
gem 'puma'
gem 'pg'
gem 'sequel'
gem 'rake'
gem 'bcrypt'

group :development, :test do
  gem 'rspec'
  gem 'sqlite3', '~> 1.7.3'
  gem 'database_cleaner-sequel'
  gem 'fabrication'
end
