name: Manual Deploy with Tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run backend tests
        run: docker-compose run --rm backend bundle exec rake spec
        env:
          RACK_ENV: test

  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest
    needs: test

    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/Licentra

            git checkout ${{ github.event.inputs.branch }}
            git pull origin ${{ github.event.inputs.branch }}

            docker-compose -f docker-compose.yml pull

            docker-compose -f docker-compose.yml --profile proxy up -d --build --force-recreate

            docker image prune -f
